### PR TITLE
Scipy version differ in both requirements

### PR DESCRIPTION
**Pull request by jjkoehorst**
I was looking for how to integrate biopython + python3.4 into galaxy and saw this minor version differ. |f someone just copy paste it things might go wrong or not?

### CODE REVIEW

**Comment by peterjc** [comment]
Thanks for making the README file example consistent, merged :)

I wasn't aware Galaxy was allowing tool dependencies using Python 3 yet (while getting Galaxy itself to run on Python 3 is a still a long way away). Have I missed some news?

**Comment by jjkoehorst** [comment]
I am hoping it allows it as I need python3.4 and rdflib to work together and was investigating this issue. Otherwise I need to remaster quite some code or let the user install all these libraries manually…

Jasper Koehorst
Wageningen UR

**Comment by bgruening** [comment]
@jjkoehorst I'm working currently on an entire stack based on python3. But this can take a little bit more time. This is all very experimental. Have a look at: https://github.com/galaxyproject/tools-iuc/blob/master/test_repositories/setup_python_environment_with_python3/tool_dependencies.xml

I think I also need to improve the python3 build. Help is very much appreciated.

**Comment by jjkoehorst** [comment]
Thanks, looking forward to help you. One question, as I am relatively new to tool packaging for galaxy, what is the best way to perform tests to see if it works? Have a clean system and restart galaxy overtime or what is the best way?

Jasper Koehorst
Wageningen UR

**Comment by bgruening** [comment]
Good question. We are currently working on a improved developer experience in various projects:
- https://github.com/galaxyproject/planemo-machine
- https://github.com/galaxyproject/planemo

My workflow is currently that I put the tool_dependencies.xml file into the Test Tool Shed and installing it into a Galaxy enabled Docker instance (https://github.com/bgruening/docker-galaxy-stable).

**Comment by peterjc** [comment]
For testing tool dependencies and packages (like Biopython), I would use a local Tool Shed or simply the Test Tool Shed, and some tool which uses the dependencies and has functional tests.

See also https://wiki.galaxyproject.org/Tools/BestPractices

This discussion might be best continued on the galaxy-dev mailing list: http://dev.list.galaxyproject.org/

**Pull request merged**
